version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    reviewers:
      - "iamando"
    assignees:
      - "iamando"
    labels:
      - "dependencies"
      - "gomod"
