theme: jekyll-theme-cayman
title: Logaro
description: Logaro is a lightweight Go package for JSON-based logging. It provides a simple and flexible logging solution with support for log levels, log entry customization, and hierarchical loggers.
