theme: jekyll-theme-cayman
title: Logaro
description: A flexible and lightweight logging package for Go that simplifies the process of logging events in your applications. With Logaro, you can easily incorporate comprehensive logging capabilities into your codebase.
